name: ZamowienieX
version: '0.1-Zamowienie'
main: pl.syntaxdevteam.zamowieniex.ZamowienieX
api-version: '1.20'
authors: [ f1lipuss ]
description: Plugin stworzony na testa

commands:
  zamowienie:
    description: podstawowa komenda pluginu
    usage: /zamowienie <subcommand>
    aliases: [zex, zx]
